# Generated by Django 4.0.5 on 2022-08-20 22:12

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(help_text='Enter the name of album.', max_length=50, primary_key=True, serialize=False)),
                ('release_date', models.DateField(help_text='Enter release date of the album.')),
                ('cover', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
            ],
            options={
                'ordering': ['release_date', 'name', 'artist'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('first_name', models.CharField(help_text='Enter the first name of artist.', max_length=30)),
                ('middle_name', models.CharField(help_text='Enter the middle name of artist.', max_length=30)),
                ('last_name', models.CharField(help_text='Enter the last name of artist.', max_length=30)),
                ('name', models.CharField(help_text='Enter the professional name of artist.', max_length=30, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(help_text='Enter date of birth of artist.')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='artists')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('name', models.CharField(help_text='Enter name of the music chart.', max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(help_text='Enter the country which the chart belongs to.', max_length=50)),
                ('flag', models.ImageField(upload_to='flags')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_position', models.IntegerField(default=0, help_text='Enter the peak position charted by the album.')),
                ('weeks_on_chart', models.IntegerField(default=0, help_text='Enter the number of the weeks album appeared on the chart.')),
                ('album', models.ForeignKey(help_text='Select the album.', on_delete=django.db.models.deletion.CASCADE, to='sol.album')),
                ('chart', models.ForeignKey(help_text='Select a music chart.', on_delete=django.db.models.deletion.CASCADE, to='sol.chart')),
            ],
            options={
                'ordering': ['chart', 'peak_position', 'weeks_on_chart'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(help_text='Select artist of the album.', on_delete=django.db.models.deletion.CASCADE, to='sol.artist'),
        ),
    ]
